spring:
    cloud:
        gateway:
            server:
                webflux:
                    routes:          
                    - id: msvc-products
                      uri: lb://msvc-products
                      predicates:
                      - Path=/api/products/**
                      filters:
                      - StripPrefix=2
                    - id: msvc-itemsv2
                      uri: lb://msvc-itemsv2
                      predicates:
                      - Path=/api/items/**
                      filters:
                      - StripPrefix=2                      