spring:
    cloud:
        gateway:
            server:
                webflux:
                    routes:          
                    - id: msvc-products
                      uri: lb://msvc-products
                      predicates:
                      - Path=/api/products/**
                      filters:
                      - StripPrefix=2
                      - name: SampleCookie
                        args:
                            message: Hola mi mensaje personalizado para producto
                            name: user
                            value: Daniel
                    - id: msvc-itemsv2
                      uri: lb://msvc-itemsv2
                      predicates:
                      - Path=/api/items/**
                      filters:
                      - StripPrefix=2
                      - AddRequestHeader=token-request, abcdef
                      - AddResponseHeader=token-response, 123456
                      - AddRequestParameter=name, Daniel             